### PR TITLE
update Chart of Accounts example for tighter validation

### PR DESCRIPTION
**Pull request by rizwansaeed**
# Pull Request Checklist

- [x] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [x] Tests pass
- [x] Raised the PR against the `develop` branch

# Description of the PR

update Chart of Accounts example for tighter validation

### CODE REVIEW

**Comment by jyaffe** [comment]
Do you want to reset the kernel and have execution counts start from 0?

**Review by jyaffe — DISMISSED** [review]
I've approved but would be good to reset the execution count.

**Comment by rizwansaeed** [comment]
thanks @jyaffe, have updated

**Review by jyaffe — APPROVED** [review]

**Pull request merged**
