### PR TITLE
add backtesting nb

### PR DESCRIPTION
**Pull request by slemasne**

### CODE REVIEW

**Comment by MikeMcGarry** [comment]
Cell [6]: In mapping optional you have location. That is not an optional parameter on creating a portfolio. If you want to add it you need to add it as a property by specifying property_columns=["location"] in cell 7. 

Also your required mapping has description and created which are both optional mappings. It will still work as you know but we should ensure that only required fields are in the required mapping for consistency. You can see which are which here https://www.lusid.com/docs/api/#operation/CreatePortfolio

**Comment by MikeMcGarry** [comment]
Cell [9]: As a formatting tip you should remove all the empty lines in the mapping_required and identifiers dictionary. I would do this wherever you have a dictionary. Resource for style here https://www.python.org/dev/peps/pep-0008/

**Comment by MikeMcGarry** [comment]
Cell [10]: In your arguments in a function call there should be no space between the equals sign e.g. api_factory=api_factory is preferred over api_factory = api_factory.

**Comment by MikeMcGarry** [comment]
Cell [12]: How come you used $0 for the portfolio cost and amount here? This means in LUSID that you paid nothing for these stocks. Perhaps use the current market value at this point instead? I think it might be good to show a pie chart for each portfolio so it is clear the difference in holdings compared to market value. You don't have anything in your holdings to make it clear that it is 55% weighted by market value to Alphabet.

**Comment by MikeMcGarry** [comment]
Call [14]: You use the constant flag "$unit" later on for the quote so you can take this out of your quote dataframe. You also use DataScope as the provider but have LUSID in the dataframe, might be worth taking this out too. 

Honestly all you really need in the DataFrame (CSV file) is date, price and id.

**Comment by MikeMcGarry** [comment]
Cell [15]: Formatting looks way off. Try pressing enter between apply( and lambda to put this on a new line.

**Comment by MikeMcGarry** [comment]
Cell [16] / Cell [17]: When loading quotes you do not need to provide an identifier mapping. The identifier is in the required mapping.

**Comment by MikeMcGarry** [comment]
Cell [18]: Why the try, except here? You should try and avoid these as much as possible.

**Comment by MikeMcGarry** [comment]
Cell [19]: Nice!

**Comment by MikeMcGarry** [comment]
Cell [22]: Instead of 
 lusid.models.create_derived_transaction_portfolio_request.CreateDerivedTransactionPortfolioRequest

this should be 
 lusid.models.CreateDerivedTransactionPortfolioRequest

**Comment by MikeMcGarry** [comment]
Cell [22]: parent_portfolio_id = {"code": parent_port,
                               "scope": scope}

should be parent_portfolio_id = lusid.models.ResourceId(scope=scope, code=parent_port)

Does it actually work just as a dictionary??

**Comment by MikeMcGarry** [comment]
Cell [22]: I would change this to do

try:
   api_factory.build(lusid.api.PortfoliosApi).get_portfolio(
      scope=scope,
      code=new_port)
   print (f"Portfolio {new_port} already exists in LUSID")
except lusid.exceptions.ApiException as e:
    if e.status == 404:
       response = derived_api.create_derived_portfolio(scope=scope, portfolio = derived_request)

This way if creation fails for some other reason you won't suppress an error.

**Comment by MikeMcGarry** [comment]
Cell [24]: For your holding adjustment here you can just use your Ticker, ClientInternal or QuotePermId. No need to resolve to a LUID. Saves some complexity

**Comment by slemasne** [comment]
> Cell [12]: How come you used $0 for the portfolio cost and amount here? This means in LUSID that you paid nothing for these stocks. Perhaps use the current market value at this point instead? I think it might be good to show a pie chart for each portfolio so it is clear the difference in holdings compared to market value. You don't have anything in your holdings to make it clear that it is 55% weighted by market value to Alphabet.

Thanks for feedback.

(1) For simplicity I added a cost of $0. To simulate an asset transfer. That wasn't very clear. I will update with a purchase price and cost now.

(2) Good idea on pie-chart. I will add that.

**Comment by slemasne** [comment]
> Cell [18]: Why the try, except here?

The get_aggregation_by_portfolio fails if you try and use a quote on a weekend or bank holiday when there is no quote. I use try except to skip these days.

**Comment by slemasne** [comment]
> Honestly all you really need in the DataFrame (CSV file) is date, price and id.

Good idea - done!

**Comment by slemasne** [comment]
> lusid.models.ResourceId(scope=scope, code=parent_port)

The dict actually did work. I just copied this straight from doc.lusid.com. 

That said, I updated to Resource object, this looks better for consistency.

**Comment by slemasne** [comment]
> Cell [24]/[25]: For your holding adjustment here you can just use your Ticker, ClientInternal or QuotePermId. No need to resolve to a LUID. Saves some complexity

Good idea - Ticker is best. Much clearer.

**Pull request merged**
