### PR TITLE
CTECH-3308: Update base image to latest python version

### PR DESCRIPTION
**Pull request by adamMQM**
# Pull Request Checklist

- [x] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [x] Tests pass
- [x] Raised the PR against the `develop` branch
- [x] Notebook outputs do not contain any priviledged data

# Description of the PR

### CODE REVIEW

**Comment by rizwansaeed** [comment]
the build hasnt run any of the notebooks (because none of them have changed), i'm sure they'll be find but is there a way to run them all to confirm?

**Comment by adamMQM** [comment]
This docker image actually isn't use to run the notebooks in tests, its just provided as a convenience for users

**Review by rizwansaeed — APPROVED** [review]

**Pull request merged**
