### PR TITLE
CTECH-2829 Add notebook for R03001

### PR DESCRIPTION
**Pull request by MikeMcGarry**
# Pull Request Checklist

- [ ] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [ ] Tests pass
- [x] Raised the PR against the `develop` branch

# Description of the PR

Describe the code changes for the reviewers, explain the solution you have provided and how it fixes the issue

### CODE REVIEW

**Comment by rizwansaeed** [comment]
was there meant to be some content for this?

**Comment by MikeMcGarry** [comment]
> was there meant to be some content for this?

Just the introduction and summary. No code execution.

**Pull request merged**
