### PR TITLE
CTECH-2652 fix dates as strings (for cut labels) 

### PR DESCRIPTION
**Pull request by rizwansaeed**
# Pull Request Checklist

- [x] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [x] Tests pass
- [x] Raised the PR against the `develop` branch

# Description of the PR

fix dates as strings (for cut labels)

### CODE REVIEW

**Review by adamMQM — APPROVED** [review]
LGTM

**Review by pms1969 — APPROVED** [review]
/LGTM

**Pull request merged**
