### PR TITLE
Dev 4545

### PR DESCRIPTION
**Pull request by jude-hunt**

### CODE REVIEW

**Comment by MikeMcGarry** [comment]
Nice work, looking over it now!

**Comment by MikeMcGarry** [comment]
At your description at the top

"Instead of providing a date, time, and time zone in every transaction," perhaps change "transaction" to something more generic such as "instance" as they are not only used on transactions.

Where you have "representing a daily cut-off times." drop the "a" as it doesn't fit.

In your example should both represent Singapore Close to show how cut labels replace the time and timezone?

Change "Setting Up Cut Labels" to "Set Up Cut Labels" to keep your tense consistent across the steps.

**Comment by MikeMcGarry** [comment]
You mentioned that you can find the codes here https://nodatime.org/TimeZones. However some of your cut labels use codes for timezones that are not in the "Zone ID" column. How come? Also is this an industry/ISO standard?

**Comment by MikeMcGarry** [comment]
Under 1.1

"by defining the parameters of the cut label and upserting this into LUSID"

Is this an upsert method? An upsert method means 'update' or 'insert' if it is an upsert you could create it again and not get an error.

**Comment by MikeMcGarry** [comment]
I really like your idea of using three points in the day in three different offices. It looks like your image is missing though showing the times. Perhaps you forgot to upload it like the CSV?

**Comment by MikeMcGarry** [comment]
In the output of cell 5 you have more cut labels than I expected from your dataframe and the one you already created for London close. Perhaps delete all the cut labels before you run the notebook so the output is what a user might expect to see.

**Comment by MikeMcGarry** [comment]
I like the wrong opening time and update bit, very likely to happen to a user.

**Comment by jude-hunt** [comment]
> You mentioned that you can find the codes here https://nodatime.org/TimeZones. However some of your cut labels use codes for timezones that are not in the "Zone ID" column. How come? Also is this an industry/ISO standard?

Good point - just checked and it also allows the Aliases column - it's an industry standard format imported from the datetime API we're using (NodaTime) - I'll add that you can include Aliases too

**Comment by MikeMcGarry** [comment]
Under section 2. you have "and in order to create a portfolio you will need to create a scope". 

Scopes aren't actually explicitly created, so all you need to do is define a name for your scope, so perhaps change the wording here to reflect this so users don't get confused trying to work out how to create a scope.

**Comment by MikeMcGarry** [comment]
Nice work linking to all the Knowledge Base articles.

**Comment by MikeMcGarry** [comment]
What do you mean by this line?

effective_date = datetime(2018, 1, 1, tzinfo=pytz.utc) # this could be an error ?

**Comment by MikeMcGarry** [comment]
In cell 10, unless you are going to create multiple portfolios you might want to remove adding the response to a  list

**Comment by jude-hunt** [comment]
> In the output of cell 5 you have more cut labels than I expected from your dataframe and the one you already created for London close. Perhaps delete all the cut labels before you run the notebook so the output is what a user might expect to see.

The cell right at the end deletes all cut labels to leave the notebook fresh after finishing the example so that should resolve it. Should I put this at the start instead?

**Comment by MikeMcGarry** [comment]
The output of cell 16 has buy and sell tranasctions. Given we haven't added any transactions yet I wouldn't expect these to be there.

**Comment by MikeMcGarry** [comment]
You have an extra cell on the last line which is empty. Delete it.

**Comment by jude-hunt** [comment]
> What do you mean by this line?
> 
> effective_date = datetime(2018, 1, 1, tzinfo=pytz.utc) # this could be an error ?

Forgot to take the comment out, was having a few bugs before and trying to sift through potential errors - deleted the comment

**Comment by MikeMcGarry** [comment]
As you 
- Add transactions
- Get transactions
- Get holdings

Three times, once for each office, it might be worth creating a function for each of these with the datetimes and the transactions as inputs. Then the focus will be more on the cut labels and less repetitive.

**Comment by jude-hunt** [comment]
> As you
> 
> * Add transactions
> * Get transactions
> * Get holdings
> 
> Three times, once for each office, it might be worth creating a function for each of these with the datetimes and the transactions as inputs. Then the focus will be more on the cut labels and less repetitive.

Really good idea, I'll sort that now

**Pull request merged**
