### PR TITLE
CTECH-2656 Added notebook for T09004

### PR DESCRIPTION
**Pull request by MikeMcGarry**
# Pull Request Checklist

- [ ] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [ ] Tests pass
- [x] Raised the PR against the `develop` branch

# Description of the PR

Describe the code changes for the reviewers, explain the solution you have provided and how it fixes the issue

### CODE REVIEW

**Comment by MikeMcGarry** [comment]
I can see the test failed due to the subscription already existing. Will update this notebook and the others to have some logic to check if the subscription already exists at the start as well to mitigate this.

**Review by rizwansaeed — APPROVED** [review]

**Pull request closed without merging**
