### PR TITLE
Feature/se 2801.transaction type consolidation nb

### PR DESCRIPTION
**Pull request by Tomwp**
# Pull Request Checklist

- [x] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [x] Tests pass
- [x] Raised the PR against the `develop` branch

# Description of the PR

Describe the code changes for the reviewers, explain the solution you have provided and how it fixes the issue

### CODE REVIEW

**Review by jyaffe — APPROVED** [review]
/LGTM

**Comment by Tomwp** [comment]
Closing PR. Will open a new one for this notebook.

**Pull request closed without merging**
