### PR TITLE
Portfolios module

### PR DESCRIPTION
**Pull request by dariadelu**

### CODE REVIEW

**Comment by MikeMcGarry** [comment]
In the first text cell at the very top I would change it from '...are the main containers' to 'are used to contain' as I don't know of any other containers for holdings transactions. Also I'd remove the holdings bit as portfolios actually don't contain holdings only transactions and the holdings are calculated on the fly.

**Comment by MikeMcGarry** [comment]
Add headers to each section for each of the items in the list that you have at the top. This will break the notebook up a little better.

**Comment by MikeMcGarry** [comment]
In cell [3] I see that you've mentioned getting the scope from the portfolio csv but then it is hard coded in?

**Comment by MikeMcGarry** [comment]
MM
[4] Can you move any of these functions into the sample_data.py file and import them? For the ones you can't let's just do it outside the function, verbosity is a good thing in these examples compared with typical programming.

**Comment by MikeMcGarry** [comment]
For the article links throughout the notebook let's link to the article itself rather than the list of articles and let's use the format LUSID Knowledge Base: {topic_name} as the text for the link e.g. LUSID Knowledge Base: Derived Portfolios

**Comment by MikeMcGarry** [comment]
Let's add a line in italics at the end of every block of text which explains what the cell below will do in the format

_Run the cell below to ......_

For example

_Run the cell below to get compare the details between our parent and derived portfolios_

**Comment by MikeMcGarry** [comment]
[11] Let's print the portfolio group response again using pretty print here rather than printing the object.

**Comment by dariadelu** [comment]
> MM
> [4] Can you move any of these functions into the sample_data.py file and import them? For the ones you can't let's just do it outside the function, verbosity is a good thing in these examples compared with typical programming.

Surely moving the helper functions to a separate file is hiding the logic and less verbose? I'm pretty sure I can move all of them but then things will magically be created/deleted from a list of portfolios

**Comment by MikeMcGarry** [comment]
[14] It looks like you have accidentally retrieved the portfolios for populated_group1 instead of populated_group2

**Comment by MikeMcGarry** [comment]
[17]
The expanded_portfolio_group_response pretty print function should say something other than 'Portfolio Created' for each portfolio. Perhaps 'Portfolio in Group'?

**Comment by MikeMcGarry** [comment]
[18]
Nothing to change atm however to let you know, I've put in a ticket to have delete_portfolio_from_group use a ResourceId like the other methods. Currently it has two separate arguments, one for scope and one for code. No reason it should be different.

**Comment by MikeMcGarry** [comment]
[22], [23], [24], [26], [27], [28] - Can we create pretty print functions for these?

**Comment by MikeMcGarry** [comment]
[2] Why do we set the headers to a variable, we never use it anywhere else in the notebook. Probably no point doing this and printing as the information is easily accessible from the .head() call.

**Comment by MikeMcGarry** [comment]
[6]
Can we update the pretty print function to print the scope of the parent portfolio as well as the code, looks like I missed that when I created that function

**Comment by MikeMcGarry** [comment]
[12] The two responses are the same, what happened to the derived portfolio on the updated response?

**Comment by MikeMcGarry** [comment]
[13] How come the populated response has no portfolios?

**Comment by MikeMcGarry** [comment]
[4] Remove awkward extra line spacing between comments and functions

**Comment by MikeMcGarry** [comment]
[10] For this one, in your comments above the cell you mention we need to explicitly remove them in order then in the notes you say it is okay to remove a group that has portfolios. What is the exact behaviour?

**Comment by MikeMcGarry** [comment]
[21] Perhaps print some headings here to show which response belongs to which group

**Comment by MikeMcGarry** [comment]
[23] How come there are two derived portfolios here but we only ever create one earlier? Also might be worth changing the pretty print function to use a word other than created above each portfolio as we haven't created them here, just listed them

**Comment by MikeMcGarry** [comment]
[25] Is it necessary to create portfolios_to_keep here? Why not just define parents_to_keep and derived_to_keep directly and save a few lines

**Comment by dariadelu** [comment]
> [4] Remove awkward extra line spacing between comments and functions

This is caused by the PEP8 formatting tool, apparently correct format requires 2 lines of space between comments and code, and around functions

**Comment by dariadelu** [comment]
> [10] For this one, in your comments above the cell you mention we need to explicitly remove them in order then in the notes you say it is okay to remove a group that has portfolios. What is the exact behaviour?

Because reverting changes requires you to do so step by step eg you want to take 1 portfolio out and put it into another group as opposed to deleting the group and ending up with n ungrouped portfolios?  There's no undo button so to undo an action you have to do the reverse of each step - the note just clarifies that if you don't care about undoing each step you can just get rid of a group without it affecting the portfolios? Does that make sense? Dunno how to reword that block without waffle

**Comment by dariadelu** [comment]
> [25] Is it necessary to create portfolios_to_keep here? Why not just define parents_to_keep and derived_to_keep directly and save a few lines

This was originally automatically populated from a group, I changed it to manually setting one derived/parent pair for simplicity's sake, I guess its not technically needed anymore other than to be consistent with portfolios_to_delete and splitting that up.

**Comment by dariadelu** [comment]
> [23] How come there are two derived portfolios here but we only ever create one earlier? Also might be worth changing the pretty print function to use a word other than created above each portfolio as we haven't created them here, just listed them

there are portfolios lingering in the scope from the previous run - usually just the one parent/derived pair that's in the 'portfolio_to_keep' list - since the scope isn't unique, only the codes are. Sometimes if I'm running cells multiple times I end up with loads of extra portfolios. This is explained in the text description above. Even running the notebook for the first time you'll find that parent/derived pair in the scope to begin with as a minimum unless you create a completely new scope

**Pull request merged**
